eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: user
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      database: user_db
      port: 27017
server:
  port: 3005
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  circuitBreaker:
    enable: true